config/routes.rb
Huanhao::Application.routes.draw do


  resources :images_indices

  resources :goods do
     collection do
        post :add_new
      end
  end
  resources :goods_types

  resources :images_indices

  resources :question_result_details

  resources :question_results

  resources :web_infos

  resources :question_details

  resources :question_categories

  

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  resources :applies

  resources :page_temps

  resources :course_types

  resources :courses


  resources :adds

  resources :friend_links

match '/', :to => 'homes#index'
match '/homes/forums/:id/:page',  
  :controller => 'homes',  
  :action => 'forums',  
  :requirements => {:id=>/\d+/,:page => /\d+/},  
  :page => nil ,
  :id => nil  

 match '/homes/articles/:id',  
  :controller => 'homes',  
  :action => 'articles',  
  :requirements => {:id=>/\d+/},  
  :id => nil  


 match '/homes/courses/:id',  
  :controller => 'homes',  
  :action => 'courses',  
  :requirements => {:id=>/\d+/},  
  :id => nil    

match '/homes/forums/:id/',  
  :controller => 'homes',  
  :action => 'forums',  
  :requirements => {:id=>/\d+/},  
  :id => nil  

  match '/homes/goods/:id/',  
  :controller => 'homes',  
  :action => 'goods',  
  :requirements => {:id=>/\d+/},  
  :id => nil  

  match '/homes/goods/:id/:page',  
  :controller => 'homes',  
  :action => 'goods',  
  :requirements => {:id=>/\d+/,:page => /\d+/},  
  :page => nil ,
  :id => nil  
  resources :events
  resources :homes do
      collection do
        get :apply
        get :forums
        get :goods
        get :articles
        get :read
      end
  end


  resources :questions do
    collection do
      get :save_question
    end
  end


  resources :question_bases do
    collection do
      post :answer
    end
  end


  resources :admin do
      collection do
        get :delete_cache
      end
  end

  resources :forums do
  collection do
  get :select_with_ajax
  post :select_with_ajax
  end
  end
  
  resources :articles do
     collection do
        post :add_index
      end
  end


  get "admin/dashboard"

  resources :users do
    collection do
      post :login
      get  :login
      get :logout
      
    end
  end
  
end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  validates_presence_of :name,:message => "登录名不为空"
  validates_presence_of :password,:message => "密码不为空"
  validates_presence_of :password_comfire,:message => "密码重复不为空"
  validates_presence_of :email,:message => "邮箱地址不为空"
  validates_uniqueness_of :name,:message => "登录名已经被使用"
  validates_uniqueness_of :email,:message => "邮箱已经被使用"
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,:message => "请输入正确的邮箱格式"
  validates_format_of :name, :with => /^[a-zA-Z][a-zA-Z0-9_]{4,15}$/i,:message => "登录名格式:字母开头，允许5-16字节，允许字母数字下划线"
  validates_format_of :password, :with => /^[a-zA-Z0-9_]{5,15}$/i,:message => "密码格式:允许6-16字节，允许字母数字下划线"
  has_many  :use_permissions
  has_many  :permissions,:through=>:use_permissions



  attr_accessor :password_comfire
  validates_confirmation_of :password,:message => "两次输入密码不一致"
  
  def login(session)
    u = User.find_by_name_and_password(self.name,User.do_password_hash(self.password))
    if u
      session[:is_login] = true
      session[:login_name] = u.name
      session[:user_id] = u.id
    else
      errors.add(:login_name, "用户名密码错误")
      return false
    end
  end

  def self.logout(session)
    session[:is_login] = nil
  end

  def self.do_password_hash(password = nil)
    Digest::SHA1.hexdigest(password) if password
  end
  
  def before_create
    # hash the pass before creating a author
    self.password = User.do_password_hash(self.password)
  end
  def before_update
    # hash the pass before creating a author
    self.password = User.do_password_hash(self.password)
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  layout "admin"
  
  def index
    @users = User.paginate :page => params[:page]||1,
                            :per_page=>10,
							:conditions=>["name like ?",params[:name]? "%#{params[:name]}%":"%"],
                            :order => 'updated_at DESC'
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  def login
    @user = User.new(params[:user])
   if !request.post?
   render "login",:layout=>"login"
   return 
    end
    if @user.login(session)
      flash[:notice] = "Hello! #{@user.name},"+ I18n.t('welcome_word')
       redirect_back_or_default "/articles"
    else
       @error_msg = "用户名/密码错误"
       render "login",:layout=>"login"
    end
   
  end

  
  
  def logout
    User.logout(session)
    redirect_back_or_default ('/users/login')
  end
  
  def forget_password
    user = User.find_by_email(params[:email])
    if user
      Mailer.delay.deliver_get_password(user)
      flash[:notice] = I18n.t('password_send')
    else
      flash[:notice] = I18n.t('no_email')
    end
    @user = User.new()
    render :action=> "login"
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div id="page" style="min-height: 500px">
  <!-- Wrapper -->
  <div class="wrapper">
    <!-- Left column/section -->
    <section class="column width6 first">					

      <h3>新增用户</h3>
      <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
          <div class="box box-info"><%=msg%></div>
        <% end %>
      <%end%>

      <%= simple_form_for(@user) do |f| %>
        <fieldset>
          <legend>新增用户</legend>

          <p>
            <label class="required" for="name">登录名</label><br>
            <%= f.text_field :name,:class=>"half" %>
          </p>

          <p>
            <label class="required" for="password">密码：</label><br>
            <%= f.password_field :password,:class=>"half",:value=>""%>
          </p>

          <p>
            <label class="required" for="password_comfire">密码确认:</label><br>
            <%= f.password_field :password_comfire,:class=>"half" %>
          </p>

          <p>
            <label class="required" for="email">邮箱</label><br>
            <%= f.text_field :email,:class=>"email" %>
          </p>

          <p>
            <label class="required">权限:</label><br>
            <%= f.association :permissions, :as=>:check_boxes, :input_html => { :size=>6 } %>
          </p>

          <p class="box"><input type="submit" class="btn btn-green big" value="提交"> or <input type="reset" class="btn" value="重置">
            <%= link_to '返回', users_path,:class=>"btn btn-green big" ,:style=>"vertical-align: middle;margin-bottom: 0;"%></p>

            </fieldset>

          <%end%>

          </div>
          <!-- End of Wrapper -->
          </div>

app/views/users/_login_form.erb
<% form_for @user, :url => { :action => "/users/login" }, :method => :post do |f| %>
  <div id="login" <%if @signup%> class="hidden" <%end%>>
    <div id="login_form" >
      <h1><%= t 'Log-in your Account' %></h1>
      <div class="row clear">
        <label for="user_login"> 登录名:</label>
        <%= f.text_field :name%>
        <div class="clear"></div>
      </div>
      <div class="row clear">
        <label for="user_login"> 密码</label>
        <%= f.password_field :password,:label => "密码" %>
        <div class="clear"></div>
      </div>
      <div class="button">
        <%= f.submit "登录", :class=>'button' %>
      </div>
    </div>

    <div id="forgot_form" class="hidden">
      <h1><%= t 'Retrieve My Password' %></h1>
      <div class="instruction"><%= t 'Enter email address and your password will be sent to you' %></div>
      <p>
        <%=t("Enter Email Address")%>:
        <%= f.text_field :email %>
      </p>
      <div class="button">
        <%= f.submit t('Retrieve Password'), :class => 'button' %>
      </div>
    </div>
    <div class="instruction">
      <span>
        <%= t "I forgot my password" %>
        <a href="#" id="forgot_password_clicker" style="display: inline;" class ="a2" >
          <%= t "password" %>
        </a>
      </span>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div id="page">
  <!-- Wrapper -->
  <div class="wrapper">
    <!-- Left column/section -->
    <section class="column width6 first">					
      <div class="clear">&nbsp;</div>
      <div class="dataTables_wrapper" id="example_wrapper">
        <div id="add_user" class="dataTables_length"><%= link_to '新增用户', new_user_path %></div>
        <div id="example_filter" class="dataTables_filter">
         <form action="/users",method="get">
          根据登录名查找: <input type="text" name = "name" value="<%=params[:name]%>">
		  <input type="submit" class="btn btn-green big" value="提交">
		  </form>
		  </div>
		   <table class="display stylized" id="example">
          <thead>
            <tr>
              <th style="width: 125px;">登录名</th>
              <th style="width: 137px; ">邮箱</th>
              <th style="width: 137px; ">查看</th>
              <th style="width: 170px; ">编辑</th>
              <th style="width: 107px; ">删除</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr class="gradeA odd">
              <td><%= user.name %></td>
              <td><%=user.email%></td>
              <td><%= link_to '查看', user %></td>
              <td><%= link_to '编辑', edit_user_path(user) %></td>
              <td><%= link_to '删除', user, :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
          <%end%>
          </tbody>
         
        </table>
         <%= will_paginate @users , :params => {:name=> params[:name]} %>

      </div>

      <div class="clear">&nbsp;</div>

    </section>
    <!-- End of Left column/section -->

          <!-- End of Right column/section -->
          </div>
          <!-- End of Wrapper -->
          </div>

app/views/users/login.html.erb
<header id="top">
    <div class="wrapper-login">
      <!-- Title/Logo - can use text instead of image -->
      <div id="title"> 
中权绿化
         <!--<span>Administry</span> demo--></div>
      <!-- Main navigation -->
       <nav id="menu">
        <ul class="sf-menu">
          <li class="current">
            <a href="#">登录</a>
          </li>
        </ul>
      </nav>
      <!-- End of Main navigation -->
      <!-- Aside links -->
      <aside><b></b> &middot; <a href="#"></a> &middot; <a href="#"></a></aside>
      <!-- End of Aside links -->
    </div>
  </header>
  <!-- End of Header -->
  <!-- Page title -->
  <div id="pagetitle">
    <div class="wrapper-login"></div>
  </div>
  <!-- End of Page title -->
  
  <!-- Page content -->
  <div id="page">
    <!-- Wrapper -->
    <div class="wrapper-login">
        <!-- Login form -->
        <section class="full">          
          
         <h3>登录中权绿化cms后台</h3>
        <%if @error_msg%>
          <div class="box box-info"> <%=@error_msg%></div>
        <%end%>
              <form id="loginform" method="POST" action="login.html">

                <p>
                  <label class="required" for="username">用户名:</label>
                  <br/>    
                  <input type="text" id="username" class="full" value="" name="user[name]"/>    
                </p>

                <p>
                  <label class="required" for="password">密码:</label>
                  <br/>    
                  <input type="password" id="password" class="full" value="" name="user[password]"/>    
                </p>

                <p>
                  <input type="submit" class="btn btn-green big" value="登录"/>    
                  <!--&nbsp;
                  <a href="javascript: //;" onClick="$('#emailform').slideDown(); return false;">Forgot password?</a>
                or
                <a href="#">Need help?</a>
                -->
              </p>
              <div class="clear">&nbsp;</div>
            </form>
            <!--
              <form id="emailform" style="display:none" method="post" action="#">    
            <div class="box">
              <p id="emailinput">
                <label for="email">Email:</label>
                <br/>    
                <input type="text" id="email" class="full" value="" name="email"/>    
              </p>
              <p>
                <input type="submit" class="btn" value="Send"/>    
              </p>
            </div>
          </form>
          -->
          
        </section>
        <!-- End of login form -->
        
    </div>
    <!-- End of Wrapper -->
  </div>
  <!-- End of Page content -->
  
  <!-- Page footer -->
  <footer id="bottom">
    <div class="wrapper-login">
      <p>Copyright &copy; 2010 <b><a HREF="httpwww.zhaepi.com" title="www.865171.cn">www.zhaepi.com</a></b> | Icons by <a HREF="http://www.zhaepi.com">杭州环保产业协会</a></p>
    </div>
  </footer>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div id="page" style="height:500px">
  <!-- Wrapper -->
  <div class="wrapper">
    <!-- Left column/section -->
    <section class="column width6 first">					

      <h3>查看用户</h3>


        <fieldset>
          <legend>查看用户</legend>

          <p>
            <label class="required" for="name">登录名</label><br>
             <%= @user.name %>
          </p>


          <p>
            <label class="required" for="email">邮箱</label><br>
             <%= @user.email %>
          </p>

          <p>
            <label class="required">权限:</label><br>
			 <% @user.permissions.each do |p|%>
			 <span><input name="user[permission_ids][]" type="hidden" value=""><input checked="checked" class="check_boxes optional" id="user_permission_ids_1" name="user[permission_ids][]" size="6" type="checkbox" value="1"><label class="collection_check_boxes" for="user_permission_ids_1"><%=p.name%></label></span>
			 <%end%>
          </p>
            </fieldset>

<%= link_to '编辑', edit_user_path(@user) %> |
<%= link_to '返回', users_path %>
          </div>
          <!-- End of Wrapper -->
          </div>