config/routes.rb
Huanhao::Application.routes.draw do


  resources :images_indices

  resources :goods do
     collection do
        post :add_new
      end
  end
  resources :goods_types

  resources :images_indices

  resources :question_result_details

  resources :question_results

  resources :web_infos

  resources :question_details

  resources :question_categories

  

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  resources :applies

  resources :page_temps

  resources :course_types

  resources :courses


  resources :adds

  resources :friend_links

match '/', :to => 'homes#index'
match '/homes/forums/:id/:page',  
  :controller => 'homes',  
  :action => 'forums',  
  :requirements => {:id=>/\d+/,:page => /\d+/},  
  :page => nil ,
  :id => nil  

 match '/homes/articles/:id',  
  :controller => 'homes',  
  :action => 'articles',  
  :requirements => {:id=>/\d+/},  
  :id => nil  


 match '/homes/courses/:id',  
  :controller => 'homes',  
  :action => 'courses',  
  :requirements => {:id=>/\d+/},  
  :id => nil    

match '/homes/forums/:id/',  
  :controller => 'homes',  
  :action => 'forums',  
  :requirements => {:id=>/\d+/},  
  :id => nil  

  match '/homes/goods/:id/',  
  :controller => 'homes',  
  :action => 'goods',  
  :requirements => {:id=>/\d+/},  
  :id => nil  

  match '/homes/goods/:id/:page',  
  :controller => 'homes',  
  :action => 'goods',  
  :requirements => {:id=>/\d+/,:page => /\d+/},  
  :page => nil ,
  :id => nil  
  resources :events
  resources :homes do
      collection do
        get :apply
        get :forums
        get :goods
        get :articles
        get :read
      end
  end


  resources :questions do
    collection do
      get :save_question
    end
  end


  resources :question_bases do
    collection do
      post :answer
    end
  end


  resources :admin do
      collection do
        get :delete_cache
      end
  end

  resources :forums do
  collection do
  get :select_with_ajax
  post :select_with_ajax
  end
  end
  
  resources :articles do
     collection do
        post :add_index
      end
  end


  get "admin/dashboard"

  resources :users do
    collection do
      post :login
      get  :login
      get :logout
      
    end
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.xml
  layout "admin"
  def index
    @courses = Course.paginate :page => params[:page]||1,
                            :per_page=>10,
              :conditions=>["name like ?",params[:name]? "%#{params[:name]}%":"%"],
                            :order => 'created_at DESC'

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.xml
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.xml
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to(@course, :notice => 'Course was successfully created.') }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(@course, :notice => 'Course was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= javascript_include_tag :ckeditor %>
  <%= javascript_include_tag "prototype" %>

    <div id="page" style="min-height: 800px">
      <!-- Wrapper -->
      <div class="wrapper">
        <!-- Left column/section -->
        <section class="column width6 first">

          <h3>新增课程</h3>
          <% if @course.errors.any? %>
            <% @course.errors.full_messages.each do |msg| %>
              <div class = 'box box-info'>
                <%=msg%></div>
                <% end %>
                  <%end%>

                    <%= simple_form_for @course,:html=>
                      {:multipart=>true} do |f| %>
                      <fieldset>
                        <legend>新增课程</legend>

                        <p>
                          <label class="required" for="title">课程名称</label>
                          <br>
                          <%= f.text_field :name,:class=>"half" %></p>

                          <p>
                            <label  for="title">课程分类</label>
                            <br>
                            <%=  select  :course, :type_id,CourseType.all.collect {|p| [ p.name, p.id ]} %></p>

                            <p>
                              <label  for="title">年龄段</label>
                              <br>
                              <%=  select  :course, :age_range,[["3-6岁","3-6岁"],["7-12岁","7-12岁"],["13-18岁","13-18岁"]] %></p>

                              <p>
                                <label for="productdesc">正文</label>
                                <br/>
                                <%= f.cktext_area   :desc,:input_html =>{},:language=>"zh-cn"%></p>
                                   <label for="productdesc">页面模版</label><br/>
            <%= select( :course,:page_temp_id, PageTemp.find(:all,:conditions=>["temp_type='文章' and is_acticity=true"]).collect {|p| [ p.name, p.id ] }) %>
                                <p class="box">
                                  <input type="submit" class="btn btn-green big" value="提交">
                                  <%= link_to '返回', courses_path,:class=>
                                    "btn btn-green big" ,:style=>"vertical-align: middle;margin-bottom: 0;"%>
                                  </p>

                                </fieldset>

                                <%end%></div>
                              </div>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
                    <%= javascript_include_tag :defaults %>
                    <div id="page">
                      <!-- Wrapper -->                    
                      <div class="wrapper">
                        <!-- Left column/section -->                    
                        <section class="column width6 first">
                          <div id="add_user" class="dataTables_length">
                            <%= link_to '新增课程', new_course_path %></div>
                            <div id="example_filter" class="dataTables_filter">
                              <form action='/courses', method='get'>
                                根据课程查找:
                                <input type="text" name = "title" value="<%=params[:name]%>                    
                                ">
                                <input type="submit" class="btn btn-green big" value="提交"></form>
                            </div>
                            <table class="display stylized" id="example">
                              <thead>
                                <tr>
                                  <th style="width: 125px;">课程名称</th>
                                  <th style="width: 125px;">课程模板</th>
                                  <th style="width: 125px;">课程类别</th>
                                  <th style="width: 125px;">年龄段</th>
                                  <th style="width: 125px;">课程描述</th>
                                  <th style="width: 50px; ">查看</th>
                                  <th style="width: 50px; ">编辑</th>
                                  <th style="width: 50px; ">删除</th>
                                </tr>
                              </thead>
                              <tbody>
                                <% @courses.each do |course| %>
                                  <tr class="gradeA odd">
                                    <td>
                                      <%= course.name %></td>
                                       <%= course.page_temp.name if course.page_temp%></td>
                                      <td>
                                        <%= course.course_type.name %></td>
                                        <td>
                                         <%= course.age_range%></td>
                                          
                                          <td>
                                           <%= raw course.desc %></td>
                                            <td>
                                              <%= link_to '查看', course %></td>
                                              <td>
                                                <%= link_to '编辑', edit_course_path(course) %></td>
                                                <td>
                                                  <%= link_to '删除', course, :confirm =>'Are you sure?', :method => :delete %></td>
                                                </tr>
                                                <%end%></tbody>
                                              </table>
                                              <%= will_paginate @course , :params =>
                                                {:title=> params[:title]} %>
                                                <div class="clear">&nbsp;</div>

                                              </section>
                                              <!-- End of Left column/section -->                    

                                              <!-- End of Right column/section --> </div>
                                            <!-- End of Wrapper --> </div>
                                          </div>

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
<div id="page" style="min-height:500px">
  <!-- Wrapper -->
  <div class="wrapper">
    <!-- Left column/section -->
    <section class="column width6 first">					

      <h3>查看课程</h3>


        <fieldset>
          <legend>查看课程</legend>

          <p>
            <label class="required">课程名称</label><br>
             <%= @course.name %>
          </p>

                    <p>
            <label class="required">描述</label><br>
             <%= raw @course.desc%>
          </p>
                   		
       </fieldset>

<%= link_to '编辑', edit_course_path(@course_type) %> |
<%= link_to '返回', course_path %>
          </div>
          <!-- End of Wrapper -->
          </div>