config/routes.rb
Huanhao::Application.routes.draw do


  resources :images_indices

  resources :goods do
     collection do
        post :add_new
      end
  end
  resources :goods_types

  resources :images_indices

  resources :question_result_details

  resources :question_results

  resources :web_infos

  resources :question_details

  resources :question_categories

  

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  resources :applies

  resources :page_temps

  resources :course_types

  resources :courses


  resources :adds

  resources :friend_links

match '/', :to => 'homes#index'
match '/homes/forums/:id/:page',  
  :controller => 'homes',  
  :action => 'forums',  
  :requirements => {:id=>/\d+/,:page => /\d+/},  
  :page => nil ,
  :id => nil  

 match '/homes/articles/:id',  
  :controller => 'homes',  
  :action => 'articles',  
  :requirements => {:id=>/\d+/},  
  :id => nil  


 match '/homes/courses/:id',  
  :controller => 'homes',  
  :action => 'courses',  
  :requirements => {:id=>/\d+/},  
  :id => nil    

match '/homes/forums/:id/',  
  :controller => 'homes',  
  :action => 'forums',  
  :requirements => {:id=>/\d+/},  
  :id => nil  

  match '/homes/goods/:id/',  
  :controller => 'homes',  
  :action => 'goods',  
  :requirements => {:id=>/\d+/},  
  :id => nil  

  match '/homes/goods/:id/:page',  
  :controller => 'homes',  
  :action => 'goods',  
  :requirements => {:id=>/\d+/,:page => /\d+/},  
  :page => nil ,
  :id => nil  
  resources :events
  resources :homes do
      collection do
        get :apply
        get :forums
        get :goods
        get :articles
        get :read
      end
  end


  resources :questions do
    collection do
      get :save_question
    end
  end


  resources :question_bases do
    collection do
      post :answer
    end
  end


  resources :admin do
      collection do
        get :delete_cache
      end
  end

  resources :forums do
  collection do
  get :select_with_ajax
  post :select_with_ajax
  end
  end
  
  resources :articles do
     collection do
        post :add_index
      end
  end


  get "admin/dashboard"

  resources :users do
    collection do
      post :login
      get  :login
      get :logout
      
    end
  end
  
end

app/models/add.rb
# encoding: utf-8
class Add < ActiveRecord::Base
  validates_presence_of :name,:message => "名称不为空"
validates_presence_of :url,:message => "广告链接不为空"
  belongs_to :picture,:class_name=>"Ckeditor::Picture"
end

app/controllers/adds_controller.rb
# encoding: utf-8
class AddsController < ApplicationController
  # GET /adds
  # GET /adds.xml
   layout "admin"
  def index
    @adds = Add.paginate :page => params[:page]||1,
                            :per_page=>10,
                            :order => 'created_at DESC'

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @adds }
    end
  end

  # GET /adds/1
  # GET /adds/1.xml
  def show
    @add = Add.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @add }
    end
  end

  # GET /adds/new
  # GET /adds/new.xml
  def new
    @add = Add.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @add }
    end
  end

  # GET /adds/1/edit
  def edit
    @add = Add.find(params[:id])
  end

  # POST /adds
  # POST /adds.xml
  def create
    @add = Add.new(params[:add])
pic =  Ckeditor::Picture.create(
      :data  => params[:picture]
    )
    @add.picture_id = pic.id
    respond_to do |format|
      if @add.save
        format.html { redirect_to(@add, :notice => 'Add was successfully created.') }
        format.xml  { render :xml => @add, :status => :created, :location => @add }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @add.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /adds/1
  # PUT /adds/1.xml
  def update
    @add = Add.find(params[:id])
	if params[:picture]
	pic =  Ckeditor::Picture.create(
      :data  => params[:picture]
    )
	params[:add][:pic_id] = pic.id
	end
    respond_to do |format|
      if @add.update_attributes(params[:add])
        format.html { redirect_to(@add, :notice => 'Add was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @add.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /adds/1
  # DELETE /adds/1.xml
  def destroy
    @add = Add.find(params[:id])
    @add.destroy

    respond_to do |format|
      format.html { redirect_to(adds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/adds_helper.rb
module AddsHelper
end

app/views/adds/_form.html.erb
<div id="page" style="height:500px">
  <!-- Wrapper -->
  <div class="wrapper">
    <!-- Left column/section -->
    <section class="column width6 first">

      <h3>新增/编辑广告</h3>
      <% if @add.errors.any? %>
        <% @add.errors.full_messages.each do |msg| %>
          <div class="box box-info"><%=msg%></div>
        <% end %>
      <%end%>

      <%= simple_form_for @add,:html=>{:multipart=>true} do |f| %>
        <fieldset>
          <legend>新增/编辑广告</legend>

          <p>
            <label class="required" for="name">广告名称</label><br/>
            <%= f.text_field :name,:class=>"half" %>
          </p>

          <p>
            <label class="required" for="name">广告图片</label><br/>
            <input type="file"  name ="picture"/>
          </p>
           <p>
            <label class="required" for="name">广告链接</label><br/>
            <%= f.text_field :url,:class=>"half" %>
          </p>
          <p class="box"><input type="submit" class="btn btn-green big" value="提交"/>
            or
            <input type="reset" class="btn" value="重置"/></p>

        </fieldset>

      <%end%>
      <%= link_to 'Show', @add %> |
      <%= link_to 'Back', friend_links_path %>
  </div>

  <!-- End of Wrapper -->
</div>

app/views/adds/edit.html.erb
<%= render 'form' %>

app/views/adds/index.html.erb
<%= javascript_include_tag :defaults %>
﻿<div id="page">
  <!-- Wrapper -->
  <div class="wrapper">
    <!-- Left column/section -->
    <section class="column width6 first">
      <div class="clear">&nbsp;</div>
      <div class="dataTables_wrapper" id="example_wrapper">
        <div id="add_user" class="dataTables_length"><%= link_to '新建广告', new_add_path %></div>
        <table class="display stylized" id="example">
          <thead>
            <tr>
              <th style="width: 125px;">广告名称</th>
              <th style="width: 137px; ">广告链接</th>
              <th style="width: 137px; ">查看</th>
              <th style="width: 170px; ">编辑</th>
              <th style="width: 107px; ">删除</th>
            </tr>
          </thead>
          <tbody>
            <% @adds.each do |add| %>
              <tr class="gradeA odd">
                <td><%= add.name %></td>
                <td><%= add.url %></td>
                <td><%= link_to 'Show', add %></td>
                <td><%= link_to 'Edit', edit_add_path(add) %></td>
                <td><%= link_to 'Destroy', add, :confirm => '确定删除', :method => :delete %></td>
              </tr>
            <%end%>
          </tbody>

        </table>
        <%= will_paginate @adds,:params => {:name=> params[:name]} %>

      </div>

      <div class="clear">&nbsp;</div>

    </section>
    <!-- End of Left column/section -->

    <!-- End of Right column/section -->
  </div>
  <!-- End of Wrapper -->
</div>

app/views/adds/new.html.erb
<%= render 'form' %>

app/views/adds/show.html.erb
<div id="page" style="height:500px">
  <!-- Wrapper -->
  <div class="wrapper">
    <!-- Left column/section -->
    <section class="column width6 first">

      <h3>查看广告</h3>


      <fieldset>
        <legend>查看广告</legend>

        <p>
          <label class="required" for="name">广告名称</label><br/>
          <%= @add.name %>
        </p>

        <p>
          <label class="required" for="name">广告链接</label><br/>
          <%= @add.url %>
        </p>
                    <p>
            <label class="required"></lab广告图片el><br>
               <%= image_tag( @add.picture.url(:thumb), :alt => @add.name) if @add.picture %>
          </p>
      </fieldset>


      <%= link_to 'Edit', edit_add_path(@add) %> |
      <%= link_to 'Back', add_path %>
  </div>
  <!-- End of Wrapper -->
</div>