config/routes.rb
Huanhao::Application.routes.draw do


  resources :images_indices

  resources :goods do
     collection do
        post :add_new
      end
  end
  resources :goods_types

  resources :images_indices

  resources :question_result_details

  resources :question_results

  resources :web_infos

  resources :question_details

  resources :question_categories

  

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  resources :applies

  resources :page_temps

  resources :course_types

  resources :courses


  resources :adds

  resources :friend_links

match '/', :to => 'homes#index'
match '/homes/forums/:id/:page',  
  :controller => 'homes',  
  :action => 'forums',  
  :requirements => {:id=>/\d+/,:page => /\d+/},  
  :page => nil ,
  :id => nil  

 match '/homes/articles/:id',  
  :controller => 'homes',  
  :action => 'articles',  
  :requirements => {:id=>/\d+/},  
  :id => nil  


 match '/homes/courses/:id',  
  :controller => 'homes',  
  :action => 'courses',  
  :requirements => {:id=>/\d+/},  
  :id => nil    

match '/homes/forums/:id/',  
  :controller => 'homes',  
  :action => 'forums',  
  :requirements => {:id=>/\d+/},  
  :id => nil  

  match '/homes/goods/:id/',  
  :controller => 'homes',  
  :action => 'goods',  
  :requirements => {:id=>/\d+/},  
  :id => nil  

  match '/homes/goods/:id/:page',  
  :controller => 'homes',  
  :action => 'goods',  
  :requirements => {:id=>/\d+/,:page => /\d+/},  
  :page => nil ,
  :id => nil  
  resources :events
  resources :homes do
      collection do
        get :apply
        get :forums
        get :goods
        get :articles
        get :read
      end
  end


  resources :questions do
    collection do
      get :save_question
    end
  end


  resources :question_bases do
    collection do
      post :answer
    end
  end


  resources :admin do
      collection do
        get :delete_cache
      end
  end

  resources :forums do
  collection do
  get :select_with_ajax
  post :select_with_ajax
  end
  end
  
  resources :articles do
     collection do
        post :add_index
      end
  end


  get "admin/dashboard"

  resources :users do
    collection do
      post :login
      get  :login
      get :logout
      
    end
  end
  
end

app/models/question_category.rb
class QuestionCategory < ActiveRecord::Base
	has_many :question_details , :dependent => :destroy
end

app/controllers/question_categories_controller.rb
class QuestionCategoriesController < ApplicationController
  # GET /question_categories
  # GET /question_categories.xml
  def index
    @question_categories = QuestionCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @question_categories }
    end
  end

  # GET /question_categories/1
  # GET /question_categories/1.xml
  def show
    @question_category = QuestionCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question_category }
    end
  end

  # GET /question_categories/new
  # GET /question_categories/new.xml
  def new
    @question_category = QuestionCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question_category }
    end
  end

  # GET /question_categories/1/edit
  def edit
    @question_category = QuestionCategory.find(params[:id])
  end

  # POST /question_categories
  # POST /question_categories.xml
  def create
    @question_category = QuestionCategory.new(params[:question_category])

    respond_to do |format|
      if @question_category.save
        if request.xhr?  
        format.js
        else
       format.html # index.html.erb
        end
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /question_categories/1
  # PUT /question_categories/1.xml
  def update
    @question_category = QuestionCategory.find(params[:id])

    respond_to do |format|
      if @question_category.update_attributes(params[:question_category])
       if request.xhr?  
        format.js
        else
       format.html # index.html.erb
        end
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /question_categories/1
  # DELETE /question_categories/1.xml
  def destroy
    @question_category = QuestionCategory.find(params[:id])
    @question_category.destroy
    respond_to do |format|
      if request.xhr?  
        format.js
        else
       format.html # index.html.erb
        end
    end
  end
end

app/helpers/question_categories_helper.rb
module QuestionCategoriesHelper
end

app/views/question_categories/_form.html.erb
<%= form_for(@question_category) do |f| %>
  <% if @question_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_category.errors.count, "error") %> prohibited this question_category from being saved:</h2>

      <ul>
      <% @question_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_categories/create.js.erb
$("input[tr=<%=params[:tr_id]%>][name='question_category[id]']").attr("value","<%=@question_category.id%>");

$("input[tr=<%=params[:tr_id]%>][name='submit_button']").hide();

$("input[tr=<%=params[:tr_id]%>][name='edit_button']").attr("disabled",false)
$("input[tr=<%=params[:tr_id]%>][name='add_button']").attr("disabled",false)
$("input[tr=<%=params[:tr_id]%>][name='add_button']").attr("category_id","<%=@question_category.id%>")
$("input[tr=<%=params[:tr_id]%>][name='edit_button']").attr("category_id","<%=@question_category.id%>")
$("input[tr=<%=params[:tr_id]%>][name='edit_button']").show();
$("input[tr=<%=params[:tr_id]%>][name='del_button']").show();
$("input[tr=<%=params[:tr_id]%>][name='add_button']").show();
  var clonedtr = $("#0").clone();
  	clonedtr.show();	
      clonedtr.attr("id","<%=params[:tr_id].to_i+1%>")
        clonedtr.find("input").each( function(index, element)
                           {
                              $(element).attr("tr","<%=params[:tr_id].to_i+1%>")
                           }
                          );
        clonedtr.find("select").each( function(index, element)
                           {
                              $(element).attr("tr","<%=params[:tr_id].to_i+1%>")
                           }
                          );
  $("#example").append(clonedtr);

app/views/question_categories/destroy.js.erb
$("#<%=params[:tr]%>").remove()

app/views/question_categories/index.html.erb
<h1>Listing question_categories</h1>

<table>
  <tr>
    <th>Level</th>
    <th>Name</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @question_categories.each do |question_category| %>
  <tr>
    <td><%= question_category.level %></td>
    <td><%= question_category.name %></td>
    <td><%= question_category.number %></td>
    <td><%= link_to 'Show', question_category %></td>
    <td><%= link_to 'Edit', edit_question_category_path(question_category) %></td>
    <td><%= link_to 'Destroy', question_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question category', new_question_category_path %>

app/views/question_categories/new.html.erb
<h1>New question_category</h1>

<%= render 'form' %>

<%= link_to 'Back', question_categories_path %>

app/views/question_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Level:</b>
  <%= @question_category.level %>
</p>

<p>
  <b>Name:</b>
  <%= @question_category.name %>
</p>

<p>
  <b>Number:</b>
  <%= @question_category.number %>
</p>


<%= link_to 'Edit', edit_question_category_path(@question_category) %> |
<%= link_to 'Back', question_categories_path %>

app/views/question_categories/update.js.erb
$("input[tr=<%=params[:tr_id]%>][name='question_category[id]']").attr("value","<%=@question_category.id%>");
$("input[tr=<%=params[:tr_id]%>][name='question_category[number]']").attr("value","<%=@question_category.number%>");
$("input[tr=<%=params[:tr_id]%>][name='question_category[name]']").attr("value","<%=@question_category.name%>");